### ISSUE TITLE
Error starting container

### ISSUE THREAD

**Issue by rasodu** [fphammerle/docker-onion-service#33]
I am getting error below.
I am using docker compose to start the container.
````
tor-testnet:
    image: fphammerle/onion-service
    volumes:
      - './var/tor/onion-service:/onion-service'
    tmpfs:
      - '/tmp:mode=1777,size=4k'
    read_only: yes
    environment:
      VERSION: 3
      VIRTUAL_PORT: 80
      TARGET: 172.10.1.24:5001
      NON_ANONYMOUS_SINGLE_HOP_MODE: 1
    cap_drop: [ALL]
    security_opt: [no-new-privileges]
    cpus: 0.5
    mem_limit: 128m
    restart: unless-stopped
````

Error:
```
lnbits-tor-testnet_1  | Jun 12 01:06:03.816 [warn] /onion-service is not owned by this user (tor, 100) but by <unknown> (1000). Perhaps you are running Tor as the wrong user?
lnbits-tor-testnet_1  | Jun 12 01:06:03.816 [warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details.
lnbits-tor-testnet_1  | Jun 12 01:06:03.816 [err] Reading config failed--see warnings above.
```
